import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import { CSSProperties } from 'react';
import StoreProvider from "@/redux/StoreProvider";

export const metadata: Metadata = {
  title: "Task App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

type CustomCSSProperties = CSSProperties & {
  '--font-poppins': string;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ '--font-poppins': poppins.style.fontFamily } as CustomCSSProperties}>
      <body className={``}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}